// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/sql/sql.proto

package sql

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for SQLS service

type SQLSService interface {
	// SQL 语句
	Query(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type sQLSService struct {
	c    client.Client
	name string
}

func NewSQLSService(name string, c client.Client) SQLSService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "sql"
	}
	return &sQLSService{
		c:    c,
		name: name,
	}
}

func (c *sQLSService) Query(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "SQLS.Query", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SQLS service

type SQLSHandler interface {
	// SQL 语句
	Query(context.Context, *Request, *Response) error
}

func RegisterSQLSHandler(s server.Server, hdlr SQLSHandler, opts ...server.HandlerOption) error {
	type sQLS interface {
		Query(ctx context.Context, in *Request, out *Response) error
	}
	type SQLS struct {
		sQLS
	}
	h := &sQLSHandler{hdlr}
	return s.Handle(s.NewHandler(&SQLS{h}, opts...))
}

type sQLSHandler struct {
	SQLSHandler
}

func (h *sQLSHandler) Query(ctx context.Context, in *Request, out *Response) error {
	return h.SQLSHandler.Query(ctx, in, out)
}
